### ISSUE TITLE
Auto Enrol and Profile based cohorts

### ISSUE THREAD

**Issue by tsmbabu** [moodleuulm/moodle-local_profilecohort#19]
Hi,
When I installed this plugin. The autoEnrol Cohort plugin stops working. I like the flexibiblity of your rules but cannot afford to lose out on the autoenrol cohort plugin feature of using standard Moodle fields to enrol users into a cohort.
What do you think is the way out?

**Comment by abias** [comment]
I assume that you mean https://moodle.org/plugins/auth_mcae.
I can't tell you any reason why this plugin stops working as we don't use both in combination here.
If you can point me to a place where local_profilecohort is doing anything wrong, I will investigate it. Otherwise, it's hard for me to help you.

Apart from than, I would like to inform you that I have been in touch with the maintainer of auth_mcae before and we have put the goal to support the on-the-fly creation of cohorts by user profile field values in local_profilecohort into our backlog afterwards. If we manage to implement this sometime in the future, you might not need auth_mcae anymore at all.
