### ISSUE TITLE
The cron job is not performing

### ISSUE THREAD

**Issue by martinvivek** [moodleuulm/moodle-local_profilecohort#3]
The cron job is not perform until the updatecohort is enable in config.
But where i can go and enable the updatecohort?
I manually enabled through database. it works fine.

**Comment by abias** [comment]
Hi martinvivek,

please note that this plugin is still under development and will hopefully be finished this month. While we have it already in production, there are still some features and the instructions in README missing.

Regarding your reported issue, I don't understand completely what you want to tell me. Could you please explain your problem in more details and / or with step-by-step instructions?

Thanks,
Alex

**Comment by martinvivek** [comment]
https://github.com/moodleuulm/moodle-local_profilecohort/blob/master/classes/task/update_cohorts.php#L49-L54

if (get_config('local_profilecohort', 'updatecohorts')) {
            $manager = new profilecohort();
            $manager->update_all_cohorts_from_rules();
            set_config('updatecohorts', false, 'local_profilecohort');

If set_config('updatecohorts', false, 'local_profilecohort'); then how it will become true (means when this will become true. )

i already created cohort and some rules, initially everything works perfect. now some user profile is changed, they will not get updated, as per my knowledge due to this set_config('updatecohorts', false, 'local_profilecohort'); it is not get updated. if i change in the config_plugin database i change it to 1 then it works fine. but again changed to 0 once it got updated.

**Comment by abias** [comment]
Hi martinvivek,

now I know what you mean.

Please have a look at https://github.com/moodleuulm/moodle-local_profilecohort/blob/master/classes/profilecohort.php#L190. This is the place where the updatecohorts setting is set to true. This function is called in https://github.com/moodleuulm/moodle-local_profilecohort/blob/master/classes/profilecohort.php#L302 as soon as an admin has changed the rule set of the plugin. 

Thus, the updatecohorts setting is basically a memory of the plugin where it remembers that it has to apply all rules to all users on the next cron run. 
In contrast, changes to a single user's cohorts don't need to be processed by cron because they are directly handled by the event handler in https://github.com/moodleuulm/moodle-local_profilecohort/blob/master/classes/profilecohort.php#L144.

I hope that things are clear now.

Thanks,
Alex
