### ISSUE TITLE
enhancement in rule

### ISSUE THREAD

**Issue by martinvivek** [moodleuulm/moodle-local_profilecohort#5]
If it is possible you can add "from"- "to" or <= and >=, now we are using exact match.
so that rule list can be minimized.

**Comment by abias** [comment]
Hi martinvivek,

I assume you want to be able to create rules which match for a given range of numbers in a profile field.
Up to now, we created the available comparators to compare strings, not numbers. That's why there is no range comparator yet.

Unfortunately, we don't have the need for comparing numbers yet, so this feature request won't make it onto our own roadmap in the near future. Anyway, feel free to send us a pull request for this reasonable addition.

Thanks,
Alex

**Comment by abias** [comment]
I am closing this issue as there has been no pull request and as we don't have the need for this feature in the foreseeable future.

Cheers,
Alex
